title: Melissa Bourdages Fitness
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5625
  brandStrength: 0.0625
  rhythmicContrast: 0
  brandColors:
    - '#dee2e1'
    - '#5c6e6e'
    - '#354646'
    - '#34979c'
    - '#7fd0bb'
  lightness: 0.875
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-72563501-1
  facebook: null
name: 'Melissa Bourdages '
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.40525
layout_spectrum: 0.218638
