name: melissafitness
favicon: null
layout_spectrum: 0.95895
typography_spectrum: 0.7367
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72563501-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3a3a3a'
    - '#747474'
    - '#dadada'
    - '#b4b4b4'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
