name: 'Melissa Bourdages '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.44621
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Melissa Bourdages Fitness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72563501-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff5780'
    - '#e1d4aa'
    - '#01072b'
    - '#009f99'
    - '#00566d'
  brandStrength: 0.1875
  lightness: 0.8064516
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
