name: 'Melissa Bourdages '
favicon: null
layout_spectrum: 0.63579
typography_spectrum: 0
title: Melissa Bourdages Fitness
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72563501-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dee2e1'
    - '#5c6e6e'
    - '#354646'
    - '#34979c'
    - '#7fd0bb'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
